export const CREATE_GUESS_START = 'CREATE_GUESS_START';
export const CREATE_GUESS_SUCCESS = 'CREATE_GUESS_SUCCESS';
export const CREATE_GUESS_FAIL = 'CREATE_GUESS_FAIL';

export const FETCH_RESULTS_START = 'FETCH_RESULTS_START';
export const FETCH_RESULTS_SUCCESS = 'FETCH_RESULTS_SUCCESS';
export const FETCH_RESULTS_FAIL = 'FETCH_RESULTS_FAIL';

export const FETCH_RESULTS_BY_DAYS_WON_START = 'FETCH_RESULTS_BY_DAYS_WON_START';
export const FETCH_RESULTS_BY_DAYS_WON_SUCCESS = 'FETCH_RESULTS_BY_DAYS_WON_SUCCESS';
export const FETCH_RESULTS_BY_DAYS_WON_FAIL = 'FETCH_RESULTS_BY_DAYS_WON_FAIL';

export const FETCH_USER_SUBMITTED_NEXT_GUESS_START = 'FETCH_USER_SUBMITTED_NEXT_GUESS_START';
export const FETCH_USER_SUBMITTED_NEXT_GUESS_SUCCESS = 'FETCH_USER_SUBMITTED_NEXT_GUESS_SUCCESS';
export const FETCH_USER_SUBMITTED_NEXT_GUESS_FAIL = 'FETCH_USER_SUBMITTED_NEXT_GUESS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';